name: ng2_testing_bug
version: 0.0.1
dependencies:
  angular2: 2.0.0-beta.0
  browser: ^0.10.0
transformers:
- angular2:
    entry_points: web/main.dart
dev_dependencies:
  test: '>=0.12.6+2 <0.13.0'
  angular2_testing: '>=2.0.0-beta.0 <3.0.0'
